name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  create:
    tags:
      - 'v*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run package
  # make sure the action works on a clean machine without building
  test-action1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=500
      - uses: ./
        id: action
        with:
          skipIfNoVersionTagOnHEAD: true
      - name: Check action outcome
        if: always()
        run: |
          echo 'hasVersionTagOnHEAD: ${{ steps.action.outputs.hasVersionTagOnHEAD }}'
          echo 'changelog: ${{ steps.action.outputs.changelog }}'

  # make sure the action works on a clean machine without building
  test-action2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=500
      - uses: ./
        id: action
        with:
          skipIfNoVersionTagOnHEAD: false
      - name: Check action outcome
        if: always()
        run: |
          echo 'hasVersionTagOnHEAD: ${{ steps.action.outputs.hasVersionTagOnHEAD }}'
          echo 'changelog: ${{ steps.action.outputs.changelog }}'
